version: '3.8'

services:
  db:
    image: postgres:16.9
    environment:
      POSTGRES_DB: haggen-test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      JDBC_URL: jdbc:postgresql://db:5432/haggen-test
      DB_USER: test
      DB_PASSWORD: test
    depends_on:
      db:
        condition: service_healthy
    command: bin/app

volumes:
  db_data: