/*
 * This source file was generated by the Gradle 'init' task
 */
package co.deferworks.haggen;

import co.deferworks.haggen.core.Context;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Context.callExternalService("https://jsonplaceholder.typicode.com/todos/1");

        System.out.println(new App().getGreeting());
    }
}
